# Generated by Django 5.2.5 on 2025-09-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
