# Generated by Django 5.2.5 on 2025-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0002_alter_lesson_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=320),
        ),
    ]
