# Generated by Django 5.2.5 on 2025-09-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0004_courseenrollment_lessonprogress_quizattempt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseEnrollment",
        ),
    ]
