# Generated by Django 5.2.5 on 2025-09-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0005_delete_courseenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="optionA",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="optionB",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="optionC",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="optionD",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.CharField(max_length=1),
        ),
    ]
