# Generated by Django 5.2.5 on 2025-09-12 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0006_question_optiona_question_optionb_question_optionc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="lesson",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="Courses.lesson",
            ),
        ),
    ]
