# Generated by Django 5.2.5 on 2025-09-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0007_alter_quiz_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
    ]
