# Generated by Django 5.2.5 on 2025-09-12 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0008_quizattempt_attempts"),
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awarded_on", models.DateField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Courses.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.user"
                    ),
                ),
            ],
        ),
    ]
