# Generated by Django 5.2.5 on 2025-09-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0009_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="grade",
            field=models.IntegerField(default=0),
        ),
    ]
