# Generated by Django 5.2.5 on 2025-09-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=34)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=23)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("instructor", "Instructor"),
                            ("admin", "Admin"),
                        ],
                        max_length=13,
                    ),
                ),
            ],
        ),
    ]
