# Generated by Django 5.2.5 on 2025-09-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
